language: python
sudo: false
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
env:
- secure: "EhG2uSD2m1eGxuL2HeQewJJx7MVL4WpjrxyfiUBEgsApemD1yKJPjUnLwAyd\nbPi5HJx5ySm1TTRSvj6/yP85YLYTaJHA8OabKk7p0wFW294qcrYIDGovU7NL\n3YOqZmqN+S3XOBGFCOnByxE+pcxxWW/3/I09EgeW7D6tBPh67G0="
install:
- pip install pytest pytest-xdist 'pytest-cov>=1.8.0' pytest-capturelog memory_profiler psutil coveralls
- pip install -e .
script:
- python -mwand.version --verbose
- py.test --cov wand --boxed --durations=20
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "ircs://ssl.ozinger.org:16667#hongminhee"
    - "irc.freenode.net#wand"
    on_success: change
    on_failure: always
